steps:
  - plugin: Shell
  - name: Symlink the website
    command: 'ln -s "$SRC_DIR/docroot" /var/www/html'
  - name: Create db for website
    command: 'mysql -e \'create database drupal\''
  - name: Set db privilages
    command: 'mysql -e \'grant all on drupal.* to "root"@"localhost"\'; mysql -e \'flush privileges\''
  - name: Create local settings files
    command: 'cp assets/sites/default/settings.local.demo.php assets/sites/default/settings.local.php;'
  - name: Fix Files Folder Permissions
    command: 'chmod -R 777 /var/www/html/sites/default/files'
  - name: Site Setup
    command: 'drush site-install --root=/var/www/html dkan'
  - name: Enables configuration modules
    command: 'drush -y en custom_config environment devinci'
  - name: Switch environment
    command: 'drush env-switch local --force'
