assets:
  - .s3curl

steps:
  - name: Setup QA site
    # Currently this "Script" is not documented in probo's docs, but it fixes the issue of
    # Probo reporting back immediately that probo is completely ready when it's not. Note that
    # we need to use 'script:' instead of 'command:'
    plugin: Script
    script: |
      # Fail right away.
      set -e

      echo ""
      echo "-------> Symlink ./docroot to var/www/html:"
      echo ""
      #Set a symlink so that probo can serve the site.
      ln -s $SRC_DIR/docroot /var/www/html
      ln -s $SRC_DIR/docroot /var/www/docroot

      # Start in the right folder of our checkout (/src)
      cd $SRC_DIR


      echo ""
      echo "Build $BUILD_ID "
      echo ""

      echo ""
      echo "-------> Run 'bash dkan-init.sh':"
      echo ""
      # Install dependencies like ahoy.
      time bash dkan/dkan-init.sh dkan --deps-only
      sudo apt-get update
      sudo apt-get install libdigest-hmac-perl clamav clamav-freshclam -y

      echo ""
      echo "-------> Setup the settings.local.php file and install a fresh database."
      echo ""
      # Setup the database.
      mysql -u root -pstrongpassword -e 'create database dkan;'
      ahoy utils setup --db-user=root --db-pass=strongpassword --db-host=127.0.0.1 --db-port=3306 --db-name=dkan
      drush cc drush
      drush dl -n registry_rebuild-7.x-2.3
      # Setup CI
      if [ -f $ASSET_DIR/.s3curl ]
      then
        cp $ASSET_DIR/.s3curl ~/.s3curl
        chmod 600 ~/.s3curl
      fi
      ahoy ci setup
      ahoy ci deploy

      echo ""
      echo "The url of this build should be at:"
      echo " https://$BUILD_ID.probo.build"
      echo ""
      echo "Known Issues (1/22/2016):"
      echo " - Site may give a SQL error on initial load. Give it a few seconds and then refresh and it should work. This is due to the container apache waking up before the MYSQL. Probo.ci knows, but they say it's not at the top of the priority since few are having that issue."
      echo " - You should usually choose: the Build Permalink (blue button) for doing site QA. If you don't any new commits may blow away the site while you are viewing it as well as the data. 'View Site' Green button shows the latest build, so it can change while you are interacting with it."
      echo ""
