<?php

/**
 * @file
 * Installation setup for USDA Nal.
 */

/**
 * Disables desired modules.
 */
function data_starter_install_module_disable() {
  $modules_to_disable = array(
    'dkan_sitewide_demo_front',
  );
  module_disable($modules_to_disable);
}

/**
 * Uninstalls desired modules.
 */
function data_starter_install_module_uninstall() {
  $modules_to_uninstall = array(
    'dkan_sitewide_demo_front',
  );
  drupal_uninstall_modules($modules_to_uninstall);
}

/**
 * Reverts desired features.
 */
function data_starter_install_features_revert() {
  $features_to_revert = array(
    'visualization_entity',
    'visualization_entity_choropleth_bundle',
    'visualization_entity_geojson_bundle',
    'nucivic_data_demo_front',
    'data_story_storyteller_role',
    'visualization_entity_visualization_contributor_role',
  );
  foreach ($features_to_revert as $feature_name) {
    $feature = features_get_features($feature_name);
    $components = array_keys($feature->info['features']);
    features_revert(array($feature_name => $components));
  }
}

/**
 * Sets desired variables.
 */
function data_starter_install_variables() {
  theme_enable(array('nucivic_data'));
  variable_set('admin_theme', 'nucivic_data');
  variable_set("theme_default", 'nucivic_data');
  variable_set("site_mail", "webadmin@nansen.nuamsdev.com");
  variable_set("error_level", "0");
  variable_set("default_logo", "0");
  variable_set("default_favicon", "0");
  variable_set("maillog_send", "0");
  variable_set("dkan_dataset_form_additional_info", "0");

  variable_set("user_pictures", "0");
  variable_set("user_register", "0");

  variable_set("site_name", "QA Site for NuCivic Data Starter");

  $var = array();
  $context = '';
  $string = 'via the  <a href="http://docs.getdkan.com">DKAN API</a>';
  $var[$context][$string] = '';
  variable_set('locale_custom_strings_en', $var);
}

/**
 * Adds users.
 */
function data_starter_install_users() {
  $user_file = drupal_get_path('module', 'data_starter_install') . '/data/users.json';
  $users = file_get_contents($user_file);
  foreach (drupal_json_decode($users) as $user) {
    $fields = array(
      'name' => $user['name'],
      'mail' => $user['mail'],
      'pass' => $user['pass'],
      'status' => 1,
      'roles' => array(
        DRUPAL_AUTHENTICATED_RID => TRUE,
        $user['role'] => TRUE,
      ),
    );

    $account = user_save('', $fields);
  }
}

/**
 * Creates about page.
 */
function data_starter_install_content_about() {
  $site_description = "This is a QA Site for NuCivic Data Starter";
  $site_description = array(
      'value' => $site_description,
      'format' => 'html'
  );
  // Query for existing About Page.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'page')
        ->propertyCondition('title', 'About')
        ->execute();
  // Update node either from existence instance or from scratch.
  if (!empty($result['node'])) {
    $node = node_load($result['node'][0]);
    $node->body[$node->language][0] = $site_description;
  }
  else {
    $node = new stdClass();
    $node->type = 'page';
    $node->title = 'About';
    $node->body = array(
      LANGUAGE_NONE => array(
        $site_description
      ),
    );
  }
  node_save($node);
}
