ahoyapi: v1
usage: NuCivic Data cli app for development using ahoy.
commands:
  drush:
    usage: Run drush via ahoy (helpful for abstraction)
    cmd: ahoy cmd-proxy drush --root=docroot "{{args}}"

  build:
    usage: A series of commands for dkan development.
    import: .ahoy/site/build.ahoy.yml
    hide: true

  custom:
    usage: custom deploy commands (Deprecated after ahoy2)
    hide: true
    import: config/custom.ahoy.yml

  dkan:
    usage: A series of commands for dkan development.
    hide: true
    import: dkan/.ahoy/dkan.ahoy.yml

  diagnose:
    usage: A series of ahoy-docker setup diagnosis commands.
    import: dkan/.ahoy/diagnose.ahoy.yml
    hide: true

  doctor:
    usage: A series of ahoy-docker setup diagnosis commands.
    import: dkan/.ahoy/diagnose.ahoy.yml
    hide: true

  confirm:
    cmd: ahoy -f dkan/.ahoy/utils.ahoy.yml confirm {{args}}
    hide: true

  docker:
    usage: A series of docker commands for dkan development (experimental)
    import: dkan/.ahoy/docker.ahoy.yml
    hide: false 

  init:
    cmd: echo "ahoy.yml file already exists."
    hide: true

  cmd-proxy:
    usage: abstraction for commmands.
    cmd: |
      if [ "$AHOY_CMD_PROXY" == "DOCKER" ]; then
        ahoy docker exec "{{args}}"
      else
        {{args}}
      fi
    hide: true

  ci:
    usage: A series of commands to handle ci setup
