<?php
/**
 * @file
 * Code for the Visualization Entity Maps feature.
 */

include_once 'visualization_entity_maps.features.inc';

/**
 * Implements hook_form_alter().
 */
function visualization_entity_maps_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'eck__entity__form_add_visualization_ve_map':
    case 'eck__entity__form_edit_visualization_ve_map':
      visualization_entity_maps_attach_libraries($form);
      break;
  }
}

/**
 * Attach needed libraries to an element.
 */
function visualization_entity_maps_attach_libraries(&$element) {
  $libraries = array(
    'lodash',
    'backbone',
    'recline',
    'd3',
    'gdocs',
    'csv',
    'mustache',
    'leaflet',
    'leaflet_markercluster',
    'slickgrid',
  );

  foreach ($libraries as $library) {
    $element['#attached']['libraries_load'][] = array($library);
  }

  $module_path = drupal_get_path('module', 'visualization_entity_maps');
  $element['#attached']['css'][] = $module_path . '/css/ve_map.css';
  drupal_add_js($module_path . '/js/visualization_entity_maps_steps.js', array('weight' => 100));
  drupal_add_js($module_path . '/js/visualization_entity_maps.js', array('weight' => 102));
}

/**
 * Implements hook_entity_view().
 */
function visualization_entity_maps_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type == 'visualization' && $entity->type == 've_map') {
    $entity->content['#suffix'] = '<div id="map"></div>';
    visualization_entity_maps_attach_libraries($entity->content);
    $entity->content['#attached']['css'][] = drupal_get_path('module', 'visualization_entity_maps') . '/css/ve_map.css';
    drupal_add_js(drupal_get_path('module', 'visualization_entity_maps') . '/js/visualization_entity_maps_view.js', array('weight' => 101));
    drupal_add_js(array('visualizationEntityMaps' => array('leafletPath' => libraries_get_path('leaflet', TRUE))), 'setting');
  }
}

/**
 * Implements hook_theme().
 */
function visualization_entity_maps_theme($existing, $type, $theme, $path) {
  return array(
    'eck__entity__form_add_visualization_ve_map' => array(
      'render element' => 'form',
      'template' => 've-map-form',
      'path' => drupal_get_path('module', 'visualization_entity_maps') . '/templates',
    ),
    'eck__entity__form_edit_visualization_ve_map' => array(
      'render element' => 'form',
      'template' => 've-map-form',
      'path' => drupal_get_path('module', 'visualization_entity_maps') . '/templates',
    ),
  );
}

/**
 * Preprocess for map add form.
 */
function template_preprocess_eck__entity__form_add_visualization_ve_map(&$vars) {
  $form = $vars['form'];
  $form = visualization_entity_maps_attach_libraries($form);
  unset($vars['form']['actions']);
  unset($vars['form']['submit']);
}

/**
 * Preprocess for map edit form.
 */
function template_preprocess_eck__entity__form_edit_visualization_ve_map(&$vars) {
  $form = $vars['form'];
  $form = visualization_entity_maps_attach_libraries($form);
  unset($vars['form']['actions']);
  unset($vars['form']['submit']);
}
