<?php
/**
 * @file
 * sop_front_page.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function sop_front_page_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Croatia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0029545a-bfaf-4af9-954c-dd9b851ae4c8',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Slovak Republic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '00756645-0381-4a64-8a15-d887b1c23919',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Strictly Confidential',
    'description' => '',
    'format' => 'html',
    'weight' => 3,
    'uuid' => '008039b9-9cee-4574-8829-6d8653478f44',
    'vocabulary_machine_name' => 'data_classification',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Comoros',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0160a138-f48f-4ba2-b7c3-2cf0eed8d348',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Macao SAR, China',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '01a449dd-3050-4282-80af-7547146fb34c',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Methodology Documents',
    'description' => '',
    'format' => 'html',
    'weight' => 12,
    'uuid' => '01f88436-a5aa-4386-a85f-903d23da81c2',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Benin',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '026536c2-51e7-4e1b-aaa2-a1c87a6bec3b',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Cyprus',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '026dcf6f-038f-4676-9c1f-e83daeb193e3',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Monthly',
    'description' => '',
    'format' => 'html',
    'weight' => 2,
    'uuid' => '0316088d-b311-4726-ad64-a61f6ca591ac',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => '日本語 (Japanese)',
    'description' => '',
    'format' => 'html',
    'weight' => 5,
    'uuid' => '032799b5-005d-48e4-be9b-74c1237769c8',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Nicaragua',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '05ddc10b-7596-4ee1-a19f-d0bfa1208d69',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Middle East & North Africa',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '060fc1d0-f4d0-4c02-915d-abd31ca423f5',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'San Marino',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '064a0837-027a-43e4-9d18-1c0c13617bda',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Marshall Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '065b86df-59eb-4652-903a-324301f99e22',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Andorra',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0674711f-56ba-4d5f-8926-a18021b741bc',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Belgium',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '06ae78e7-99df-42d2-8454-fa63b66b80cf',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Español (Spanish)',
    'description' => '',
    'format' => 'html',
    'weight' => 11,
    'uuid' => '077910fe-b2ec-41f2-9ede-73fd19e1a530',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Gibraltar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '07b02355-dc61-4c76-96bc-d4613a5a2b78',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Kuwait',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '07fa66e5-ecf7-4004-975d-b2e3b5bee4cc',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Palau',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '087ae178-b9e2-42eb-bf40-74ef5aa580d2',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Annual +',
    'description' => '',
    'format' => 'html',
    'weight' => 7,
    'uuid' => '08a7cf19-c1dc-4bb8-a954-c1ff5c5a46fa',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Time Series',
    'description' => 'Maps and data for more than 120 other countries that reveal insights about populations and their behaviors.',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '08daf801-c57e-4cf2-abc0-b2628f501727',
    'vocabulary_machine_name' => 'data_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Holy See (Vatican City State)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '091b9454-0156-47af-8859-fdf3a97f2fa3',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Micronesia, Federated States of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '094f0b52-725c-4cdf-a5ef-71405fe95445',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Honduras',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0a2af0b7-79ac-4df3-b8d4-70dd06e50054',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Norway',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0ae704ce-c45c-489a-80b1-d575b0c10d0e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Latvia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0bfeee42-2235-417a-a9ad-5bb0e7b84905',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => '中文 (Chinese)',
    'description' => '',
    'format' => 'html',
    'weight' => 1,
    'uuid' => '0c26dbc4-17e7-42ce-b479-84b6c7d0c8ec',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Haiti',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0cee64ce-1d62-4003-a9b1-2d88ccc7b543',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Stateless',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0cffd24a-a6e8-48d2-8f94-103e57eadea3',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Slovenia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0d032cce-1ee5-4085-9995-abc3ecb6b96c',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Mauritania',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0d2a140a-c517-4da5-ba14-1ceb622859a7',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Zimbabwe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0d7b5cc1-0d2e-443a-9a61-f400b5daab69',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Grenada',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0eb4c92d-dbd6-4171-95fe-21cf59cf4773',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Polski (Polish)',
    'description' => '',
    'format' => 'html',
    'weight' => 9,
    'uuid' => '0ee52dda-6bd0-4269-a46c-d85058d8a74d',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Tajikistan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0f758379-085c-457e-8dc4-af1bbb4c7ae1',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Spain',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0f979578-a8c9-424c-9c15-801fab95042e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'macao sar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0fa400e6-96fe-4520-b09f-27baf7a01a28',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Korea, Republic of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0fff6447-f16d-4558-91bb-e1b79608ab05',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Guadeloupe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '10d7bb74-3ba9-4836-b768-6c2d636bb94d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Turks and Caicos Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '116f6c8e-703e-4b6e-ac6f-731ff689a8e9',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Korea, Democratic People\'s Republic of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '12e2dc5d-b6c3-4aad-951c-c3ddc6f036e5',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Reunion',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '13151249-8228-40b6-9340-38446989d8e9',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Bulgaria',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '13524282-851e-4ca5-8957-b1be3d74bf14',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Bouvet Island',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '136a8c70-20f3-4043-a33f-ac95d48003d0',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Estonia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1463325d-98b3-4deb-9239-8dab18d65a21',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'United Arab Emirates',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '14b3cf41-0878-4e9c-a656-c099912c3f4a',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Macedonia, former Yugoslav Republic of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '150438d8-291e-41c6-a3f2-a7e867fe8973',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'License',
    'description' => '',
    'format' => 'html',
    'weight' => 8,
    'uuid' => '1713a813-446c-4aad-ab22-51dbf3ce43c3',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Bahrain',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '186ed79c-3653-49d6-8bd4-39bd01a8e369',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Sri Lanka',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '189f4561-2aa3-423a-8d6b-45ade9f5cfcf',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Bosnia and Herzegovina',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '19a2be33-9d7f-4960-b93d-10970651613f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Belarus',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1c35cd1e-6ec8-4f2d-beef-e7739d51efe5',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Somalia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1c475c19-fa8e-4a57-aaf4-13546127cc9b',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'South Sudan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1d07ff7c-35a1-49a2-af22-8ab3afebb080',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Montserrat',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e5f6747-4da2-4f51-99fa-8642f923194b',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Netherlands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2024df94-44a5-454d-999d-039952cbcf31',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Tuvalu',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '20560c18-06f5-4bbd-a463-16991559ce19',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'No further updates planned',
    'description' => '',
    'format' => 'html',
    'weight' => 10,
    'uuid' => '21530dfb-7fd3-4cdc-973e-ab11470e219d',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Belize',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '22b9acb4-5303-487d-82df-d74c9e79dcb0',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Lithuania',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '243f1ad6-420a-4684-8f4b-564b9ab70b1d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Tanzania',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '245cbc03-9a6a-446e-bd2a-8a2c04a50709',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Code book',
    'description' => '',
    'format' => 'html',
    'weight' => 3,
    'uuid' => '25540c4d-bb5d-454e-b208-ceb742914ed6',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Europe & Central Asia',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '25b46b8d-a280-412f-ac61-f8f18e22f517',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Daily',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '263b7f97-52f2-4e7a-9956-525f717622a8',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Barbados',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '26898dcb-06f6-4c62-a744-a451010dad59',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Niue',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '27b889f6-ee7c-42a1-ba75-a2e796dac781',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Niger',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '28d904ea-340c-4cfa-b1db-fc0e6997e47e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Mozambique',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '29bc7b19-3577-4f9b-b6d0-d2c1c6414246',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Czech Republic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '29cfc92c-574b-4fce-8ed3-5914ad62af9e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Khmer (Cambodian)',
    'description' => '',
    'format' => 'html',
    'weight' => 8,
    'uuid' => '2a2e9d10-cbd1-4132-b2fc-77fed47331bc',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Vector',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '2a587c0d-4e8f-4dca-bfdf-36496b2886b8',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Trinidad and Tobago',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2b167056-7abb-4b71-9cb3-a309471b9f6d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Ethiopia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2b48d1c7-d5cd-49f6-ab86-9485fd99b424',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Brazil',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2be03888-9232-4b59-897f-dba774d0926d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Best Practice Document',
    'description' => '',
    'format' => 'html',
    'weight' => 2,
    'uuid' => '2d0b28ef-f265-4581-b3dc-87ef7c956b12',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Italy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2dc98514-fa1e-4583-a337-7fc1767d7a07',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Ecuador',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2dde01c8-285f-4fe3-90d2-e1415a2a1c77',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Liberia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2e81ce93-1b3e-45ea-80fd-1a4cd96f666f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Mexico',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2ecd38fa-9769-490e-a32d-cba7667f52b0',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'British Indian Ocean Territory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2f87c1cf-2b5f-4c31-b21c-af8432c82bb6',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'korea',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2fb5c0a9-5cd8-49f0-8b16-3513dd9a68a8',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Burkina Faso',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '30c42c15-3aca-473f-8a70-68abe4d2abc2',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Other',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '3121eafb-9f3f-433b-ba83-84f8667e0e8a',
    'vocabulary_machine_name' => 'data_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Chad',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '31b58c4e-c0e1-41dc-9bcb-76f60a88f645',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Guatemala',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '31cfcee3-3af7-4486-979c-19bbf732b605',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Fiji',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '32880e7b-9a46-4358-9e84-c4320af9c258',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'हिंदी (Hindi)',
    'description' => '',
    'format' => 'html',
    'weight' => 2,
    'uuid' => '32aa3a58-da1a-404b-b236-60f2152512ef',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Lebanon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '35490857-66f9-4b86-b99c-198e76692e28',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Sierra Leone',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '36e44ae0-dd26-408e-9f41-74c1d86425ec',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Learning Material',
    'description' => '',
    'format' => 'html',
    'weight' => 7,
    'uuid' => '37949253-f5d5-49a8-a80b-7e67b5ba5133',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Qatar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '39171b27-9fe0-411d-8799-4f8927c54c93',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'macedonia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a2d0cd7-e830-41df-a3b0-e10c8b1ce217',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Togo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a656959-29cb-42bf-af4a-29369a1c7552',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Mauritius',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a798eff-4ff3-4bcf-8e96-c39754a0e6ec',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Guernsey, C.I.',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3ab56278-67db-485d-8650-47245121a390',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Georgia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b09f28f-ec6b-44cb-990a-e8f4b0452439',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Pусский (Russian)',
    'description' => '',
    'format' => 'html',
    'weight' => 14,
    'uuid' => '3b0edee2-967c-4447-b932-da66af0bf376',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Confidential',
    'description' => '',
    'format' => 'html',
    'weight' => 2,
    'uuid' => '3b6ff44f-1e07-40ee-b623-54bdd0062690',
    'vocabulary_machine_name' => 'data_classification',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Europe and Central Asia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3bc60317-6be1-47f6-8788-c7ab31554e52',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'IDA',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '3bd26f76-a33c-468e-a350-2a7f4049ecdb',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Manual and Guideline Document',
    'description' => '',
    'format' => 'html',
    'weight' => 9,
    'uuid' => '3bf026a6-11a2-4d6e-b96f-e3ef68fd2cd2',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Angola',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3cedd817-ca83-487b-8639-6ea64b08ba32',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'български (Bulgarian)',
    'description' => '',
    'format' => 'html',
    'weight' => 16,
    'uuid' => '3d14194c-6b72-4a22-90fd-ce47d93e0214',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Philippines',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3d1a75c8-0c4d-487c-b1f4-c2d1f7b26df3',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Memorandum of Understanding (MOU)',
    'description' => '',
    'format' => 'html',
    'weight' => 10,
    'uuid' => '3d8e839c-046a-4981-a8ab-ef02215abf9c',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'CSV',
    'description' => '',
    'format' => 'html',
    'weight' => 2,
    'uuid' => '3da3d185-ca2c-4f9f-9b35-46462f724fc6',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Dominican Republic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3e641c69-3074-4615-ba0d-e527b44a753d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'United States Minor Outlying Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3f0f0f5a-c6a3-4075-9339-70237750d845',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Pakistan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '43e5a73e-3427-4488-a224-2d17ba51dfff',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Montenegro',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '441c36a2-c577-4fb9-8e76-661c2578f6ac',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Wallis and Futuna Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '442caa07-29f7-41ac-a512-77676cadebe9',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'French Polynesia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '44c33078-5a2b-4db6-b68c-ecc77c2aed93',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Terms of Reference',
    'description' => '',
    'format' => 'html',
    'weight' => 18,
    'uuid' => '4500915c-f967-433b-93c1-7061f0650a29',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Kazakhstan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4599bdaa-d52b-4328-84b8-e45ef0b9b725',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Equatorial Guinea',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '498ea673-7c86-457c-82de-8a3e3d4869a5',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'News Release or Announcement',
    'description' => '',
    'format' => 'html',
    'weight' => 13,
    'uuid' => '4b07cd7b-a055-447a-b531-eb1b979aee9a',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'East Asia & Pacific',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '4dbe9476-144a-4c60-8d96-1e60fc3941ba',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'American Samoa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4e5b30c7-9dfd-4798-9cd5-7a992df0b348',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Yemen, Republic of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4eef2dad-b1bb-460f-b3fe-1003030c5437',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Martinique',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4fe20f44-b70a-403c-86e1-64d10b4cfb7c',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'former yugoslav republic of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4feb6573-28cb-4702-9d8a-95fd17f4e7e7',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Affidavit of confidentiality',
    'description' => '',
    'format' => 'html',
    'weight' => 21,
    'uuid' => '53805416-e571-4159-94bd-bfd68033e51d',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Heard and McDonald Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '54b8af33-d19a-4f52-a5bd-1b3965bd6a76',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Raster',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '554dc22c-29e6-4571-a4f9-3955bf21262d',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'United States',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '56d18a83-9f0f-4a3b-9466-8d6e1386723f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'West Bank and Gaza',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '584a680d-9b99-4d27-bf1a-1221ca3b41c3',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'XLS',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '585e4121-e57f-4d5e-acbd-7632b148bfdf',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Survey',
    'description' => '',
    'format' => 'html',
    'weight' => 17,
    'uuid' => '58aeff27-b418-4290-979d-1e818e81d525',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Finland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '58d22234-0e7c-4670-b66e-211a67d2e634',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'ZIP',
    'description' => '',
    'format' => 'html',
    'weight' => 3,
    'uuid' => '5966f059-dbce-4643-973b-18384031d7af',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Greece',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '59fd9610-dcb6-44e7-ba60-3a565d50e326',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Română (Romanian)',
    'description' => '',
    'format' => 'html',
    'weight' => 19,
    'uuid' => '5a7c0aff-e294-407f-aa0c-14d17eb5d68f',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Antigua and Barbuda',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5ab7afbd-e4d1-4925-bfae-6da5216fb3b4',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Puerto Rico',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5ac46fa0-fcb8-48b0-b2b5-8b5157daa863',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Nigeria',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5af05f7c-9088-4156-95a8-2e3ed88f5e03',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Nepal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5b98ff74-66de-42af-ae90-23903e482a39',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'St. Pierre & Miquelon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5e41d8a3-50c0-4bc4-9333-ac3fc61e451f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'St. Lucia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5f113a6b-7a47-4d77-a905-25f363c2c483',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Infographic',
    'description' => '',
    'format' => 'html',
    'weight' => 6,
    'uuid' => '5f5fedbf-50ae-484e-b7f4-c6ce1f98192f',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'New Caledonia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5fd02d20-cc60-4072-a35a-cf93c5842d4f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Sweden',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '612c270b-6c29-4038-9d05-b99a3105806b',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Presentation',
    'description' => '',
    'format' => 'html',
    'weight' => 15,
    'uuid' => '61669266-d9b8-42e1-a0d9-c20cff8e2c7b',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Solomon Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6167da18-3b26-4841-83b2-fbfdb177e400',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Suriname',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6236b190-6590-40a9-82fe-fe09c221db3d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Iraq',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '62a7a763-0751-4d12-949b-4677df97a7fe',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'global',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '634b0ed7-acab-4aa5-a92d-d5224b805f42',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Guam',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '63ae87a6-8c77-45eb-96e8-15538d255990',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Australia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '64c5ff12-8d17-4556-9b37-7d849efb61c5',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Help Document',
    'description' => '',
    'format' => 'html',
    'weight' => 5,
    'uuid' => '65162e14-06c6-4535-8894-a7a17483548e',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Lesotho',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6817a512-3859-4e8d-990a-c430b41e6a4d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Dominica',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6900dcbf-6528-4404-877a-e72d92b4de9e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'South Africa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6b373f37-90a0-4ecf-9e51-cae32c031516',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Weekly',
    'description' => '',
    'format' => 'html',
    'weight' => 1,
    'uuid' => '6e3a713c-5298-4d2f-b307-f0e377260576',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Svalbard and Jan Mayen Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ec440df-8cda-416d-8151-dfb848f80e9d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Maldives',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6fb21257-da60-4e43-82e2-9bf21cf92364',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Djibouti',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7164789b-69c9-4a60-8892-8025bdc1a117',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Bermuda',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '744ff8a0-b987-480b-b54d-d07f30015fd5',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Aruba',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '75d73896-7930-48a1-a5ee-7b5439e3b6e4',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'No fixed schedule',
    'description' => '',
    'format' => 'html',
    'weight' => 9,
    'uuid' => '77160689-416c-404b-8077-8ca39fe84bfe',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Norfolk Island',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '78ae8ffa-66f5-4464-b4c8-4f1f6c2d20cb',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Iran, Islamic Republic of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7a1a8487-2466-4056-bca5-c348f7848323',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Libya',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7a6c1f0d-8360-44e3-8fd6-8d3aa7f5ecfe',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Northern Mariana Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7ac1bb9f-d1ea-4291-89ab-8a0e204b1c10',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Faroe Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7acc7842-31fd-4694-a6e8-18fd12954e96',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Malawi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7b1c318d-0763-49b2-bf8a-371eb62788f7',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'REST',
    'description' => '',
    'format' => 'html',
    'weight' => 8,
    'uuid' => '7bbbd987-4d99-4b7f-b1e7-bec1bd04b780',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Venezuela, Republica Bolivariana de',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7cbe1eb7-4c3e-4f66-92fa-ea9793d41436',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Paraguay',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7d274fd4-c3c2-438f-8db7-3ba9f5558096',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Afghanistan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7e5f47ff-0350-4395-92c4-23245234bcd5',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Cote d\'Ivoire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7eacb17a-0f66-4880-b09a-5890e4fd3f60',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Preview file',
    'description' => '',
    'format' => 'html',
    'weight' => 16,
    'uuid' => '80582ae8-900b-4fbe-a589-40a5f16aeb4c',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Landing page',
    'description' => '',
    'format' => 'html',
    'weight' => 20,
    'uuid' => '81d33aba-c56b-48f4-9077-191335de70a6',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Israel',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '85f89099-92c3-4082-91bb-b2533cadd72b',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'македонски (Macedonian)',
    'description' => '',
    'format' => 'html',
    'weight' => 7,
    'uuid' => '8851fd3f-2812-46b7-ac38-7e3208ea5d4f',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Malaysia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '88920178-bfc3-46ac-a27e-19b1d926e375',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'High income',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '88baf9c7-825b-43e1-9e00-3e2a52c4988c',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Bolivia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8b29b7c7-60df-433b-bbf5-173385056b4e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Congo, Republic of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8cc1e379-fc43-4f42-8553-b5b569acd3f5',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Official Use Only',
    'description' => '',
    'format' => 'html',
    'weight' => 1,
    'uuid' => '8e06ca74-1a2a-4e87-aaf5-d99cb9543a9b',
    'vocabulary_machine_name' => 'data_classification',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Luxembourg',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8e545f09-5fb0-4944-8940-4b4d90602516',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Latin America & Caribbean',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '8f22ba02-9917-43ef-ba41-a0bde3085448',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Virgin Islands, British',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8f7cf471-925e-4a2b-88e9-4fc213e18147',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Sao Tome and Principe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8f8456fb-6451-4ee7-8658-bc6bf53341e4',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'French Southern Territories',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '90990f63-5e40-4455-82cd-075090514590',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Guinea',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '909a23b5-a25f-43b5-aa53-2fc83667a51f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Panama',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9154d435-5b01-4257-a061-eebef97116dc',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Cabo Verde',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9156bbb6-582f-4cc7-8625-5f783cc9f6c7',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Cameroon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9188c43f-7d7f-4b9a-8ba9-a7940203d4c8',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Mongolia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '923c0206-ebc2-4524-ba4a-5a6dd9720fe1',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Argentina',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '92ef9228-4692-46c2-9217-61f35b2118a3',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Uruguay',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '92f2c87b-aae1-41ab-8ff2-911e91d1d800',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'St. Helena',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9311ce8f-17d1-4efe-8684-33e609669b9f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Quarterly',
    'description' => '',
    'format' => 'html',
    'weight' => 3,
    'uuid' => '93530d91-4af4-48f5-b2a8-9b4d7e19af70',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'PDF',
    'description' => '',
    'format' => 'html',
    'weight' => 1,
    'uuid' => '94f51a3d-7239-4c06-9c55-d08a863ca8fc',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Kenya',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '956cc369-e9ac-4d1b-ad50-4478f94d5ae7',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Denmark',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '95db6c43-0e7d-40df-9ad9-5bf678200d02',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Virgin Islands, US',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9639002a-db71-4c16-ab52-eb2895fa6140',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Triennially',
    'description' => '',
    'format' => 'html',
    'weight' => 5,
    'uuid' => '967bf87b-7e05-4dfd-83cf-46a0fbe3bbd4',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Ghana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '96a6b332-43dc-4cf1-a62e-3f82688e632b',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Myanmar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '979b8d48-33bd-4a17-ae97-ad2f7fc50e88',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Українська (Ukrainian)',
    'description' => '',
    'format' => 'html',
    'weight' => 4,
    'uuid' => '97ebfd6f-dafa-4a28-9e79-a9c921e4dac2',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Canada',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '99b384f5-c0a1-4b08-aaa1-d9fdd263940e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'S. Georgia and S. Sandwich Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e056781-958c-47fe-9a45-f15c2b41a590',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Jersey, C.I.',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e4d75a3-3814-40f8-b1b1-38b09734bdb5',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Samoa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9ec89836-812d-4b30-8a82-af48034a55d3',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Low or Middle Income',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => '9f31883a-8be7-45c3-abbd-218e68ec25fb',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Indonesia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9fd84c16-474b-4863-9cef-88cc08cc148a',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Mali',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a0bd703f-0dc6-4697-9ffe-39378360dd7d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Annually',
    'description' => '',
    'format' => 'html',
    'weight' => 6,
    'uuid' => 'a12927f0-7e73-4080-8a1f-498eb00e234c',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'republic of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a18cd559-cabf-4709-9ce6-12b4f15ee1db',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Cayman Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a1e37cfe-5515-4dc5-9d11-c9d517f44951',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Guyana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a2541fe9-3bfa-473f-a952-4cc7cc04ae2e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => '',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a3da6dc5-25ae-48ea-9c92-65f8f49e8bed',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Vietnam',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a405b4d5-401e-4d87-ab55-6a1cb8045071',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'English',
    'description' => '',
    'format' => 'html',
    'weight' => 12,
    'uuid' => 'a4784754-9d7c-4b6e-9597-bfc2494dc04c',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Tunisia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a4db9b86-9760-49cc-a9e0-d880efb46631',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Bulkdownload Dataset file',
    'description' => '',
    'format' => 'html',
    'weight' => 1,
    'uuid' => 'a4ddbd69-f6f2-438a-b41c-6ab608308f3f',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Turkmenistan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a528272a-f023-49f9-891a-a3673212400e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Tonga',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a548caf3-cd1a-4024-808b-ab07710ddd8a',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Global',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => 'a559ddae-e02b-4bff-95db-53611b7eb31b',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Christmas Island',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a7c3b519-34b0-4858-80e1-3d9500278088',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Azerbaijan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a8dbf5b4-8e45-4977-ac51-95c52eb2b75f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Kiribati',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a8eee419-79c1-46a0-8fcc-433a3d583351',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Curacao',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ac74b94f-9bf8-4519-a9bb-42a3b1506fd7',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Romania',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad0f7bb5-b7c8-448c-bc47-37d42dacc4ef',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Greenland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad606600-af14-4740-9ccf-e899acfa059d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Albania',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'adb9a3c7-2815-4be5-8273-376ac9fa637c',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Tiếng Việt (Vietnam)',
    'description' => '',
    'format' => 'html',
    'weight' => 17,
    'uuid' => 'adbd7131-2b12-4d37-859c-bb134236c77c',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Shqip (Albanian)',
    'description' => '',
    'format' => 'html',
    'weight' => 18,
    'uuid' => 'ae2dfaf7-62eb-400f-91f1-82397864a548',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Thailand',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ae91d9e1-1b75-4b7a-94ed-6bbe5ac0eb53',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Latin America & Caribbean',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aebeed77-d00b-432c-bacb-1dd14b5602d1',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Morocco',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aec8fa8d-a358-47bc-8a40-26de0c2ee7ea',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Gambia, The',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aedc6884-0de7-468b-a23d-594dbb29fc99',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Anguilla',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'af0ea840-b72d-4fdd-ba94-f0165422c0c8',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Swaziland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'af741e74-afea-48c1-9363-6a96ab102150',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Central African Republic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b0184766-79a0-4ffc-9e11-c1346ae128ba',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Jordan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b0bb6a62-c3c9-4627-a817-20a8c1ca6275',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Middle East and North Africa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b12f05ba-a7ef-4455-a346-806799b5af48',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Rwanda',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b1465637-61f8-4787-8ca7-da3e8b4ba409',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Zambia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b19d3452-8115-4556-bb26-844b35f7372e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'ภาษาไทย (Thai)',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => 'b1e5a1c1-1c30-4570-a747-35c6d3cb4af4',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Taiwan, China',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b28c0f1b-7429-4fd9-8216-29d4e1de6467',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Hong Kong SAR, China',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b3801104-2a69-4e05-833e-759f834c2df3',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Armenia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b3f6135c-6987-4859-95a4-723687352fe1',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Poland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b55df192-1e26-4301-b659-a10bc21c86c4',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Vanuatu',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b5dc133f-dd64-45dc-8452-cf195fdca0fd',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Portugal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b6225d75-b7a7-472e-8e0d-b57922e04912',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Uzbekistan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b62fb1d3-9d51-4e79-8d74-64ff858a7f7f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Microdata',
    'description' => 'This is a dynamic traffic map service with capabilities for visualizing traffic speeds relative to expected.',
    'format' => 'html',
    'weight' => 0,
    'uuid' => 'b6e20ae1-3086-4afd-b3e3-3f245612d044',
    'vocabulary_machine_name' => 'data_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Api',
    'description' => '',
    'format' => 'html',
    'weight' => 19,
    'uuid' => 'b70757f6-9098-4ba0-a8d8-094ce7abf404',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Lao People\'s Democratic Republic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b852341d-27aa-4e10-8367-2dbea9d25bc2',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'India',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b923ce63-f847-49e4-8ce0-ab2d7ee3caa1',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Oman',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b948fa60-7f7b-46cc-8ed4-46396a9ccaf9',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'IBRD',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => 'ba131518-6613-4b48-bdba-1fb2609e2ec9',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Guideline Document',
    'description' => '',
    'format' => 'html',
    'weight' => 4,
    'uuid' => 'bb0fc244-9a89-4ea0-87aa-289beff0d6a8',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Egypt, Arab Republic of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bb2704de-38f6-4dbe-b876-96471fa4b9bb',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Congo, Democratic Republic of',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bbd655a0-71ba-4544-9cf2-a83620ef8c42',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Sub Saharan Africa',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => 'bcc52246-117f-42ff-b96a-85d3ce96dbe5',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Malta',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bd513e24-d592-4722-8593-2fe460832425',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Madagascar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'be26c6fc-b469-48e2-a173-f183bd9fa7bd',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Turkey',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'beda0e44-56ff-46e8-87b9-c47f56a20d9a',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Jamaica',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bfa4976d-c4f5-4afe-b26d-7590f2c6b4b4',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Germany',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c03bc883-f4bf-4abb-bfa7-72da7bf84015',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Antarctica',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c0fc0dda-ef8c-422b-859f-e91b7380887b',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Bhutan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c13ca5f3-b78e-449a-95d7-17f919340296',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Mayotte',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c1afffba-c3da-44f5-9f58-3be5a60ab1bd',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'World',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => 'c21236e1-e51f-4077-bc25-f2ff64ecad12',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Switzerland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c299a9c3-2f9a-4ac9-9de0-d5e24758cff5',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Cambodia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c355b4c5-53ad-4652-ba0a-93f7255d570d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Biannually',
    'description' => '',
    'format' => 'html',
    'weight' => 4,
    'uuid' => 'c3f4f4d9-3114-4f54-ab82-b7af54a4eb75',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Brunei Darussalam',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c70b5372-2643-41c4-ab6a-23d2569606c3',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'United Kingdom',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c7d9cb1a-6940-45fb-bddb-311ded8b23bb',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'East Asia and Pacific',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c800bc35-8fef-445f-a830-d28e5a358c88',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'New Zealand',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c85a1f63-47ee-4e41-b554-3b46ad5d7e27',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Africa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c89d38c9-79f4-4d8e-83a8-0fb6aaf34431',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Namibia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c9f098d7-5981-494f-87f1-7b115f81b136',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Falkland Islands (Malvinas)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cac8233e-8e86-4be7-b3a1-43e051509bfb',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Hungary',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cace3665-182a-4518-929d-a5a06dfc88f7',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'PPT',
    'description' => '',
    'format' => 'html',
    'weight' => 5,
    'uuid' => 'cc0eb5e2-489d-4e22-8443-985cc53555db',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'العربية (Arabic)',
    'description' => '',
    'format' => 'html',
    'weight' => 3,
    'uuid' => 'cc301d21-1cfe-41ba-8056-5b555f53c797',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'St. Kitts and Nevis',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ccd6d153-6dca-46b8-8ad9-db47ef6da2a9',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Português (Portuguese)',
    'description' => '',
    'format' => 'html',
    'weight' => 13,
    'uuid' => 'd049901f-a538-4706-8c26-5be8d7e19ed4',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Syrian Arab Republic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd067e68d-0783-43e4-b2f1-b71188fd6c46',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Monaco',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd0d981a1-b6dc-45bf-961a-e7fdd35b5585',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Query Tool',
    'description' => '',
    'format' => 'html',
    'weight' => 23,
    'uuid' => 'd15e28d8-c292-420b-9c85-181c1a25e339',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'France',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd27b34f8-fda6-45b9-8be8-b799b8d17f5f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Isle of Man',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd33a8667-b43b-41ca-810e-23ffd023f467',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Serbia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd37de7fd-f5be-434e-bb5a-f8ec5400606e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Costa Rica',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd42969f6-db22-4347-a6ce-c64198613a1f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Burundi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd49c4f01-f06c-438b-a9b8-b8fb6b1bcdbd',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Western Sahara',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd607db47-b988-4a2a-acd9-225543b31ecd',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Guinea-Bissau',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd69c949e-bd8c-4093-b2ff-0bcd85913320',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Colombia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd6f49ac1-d450-4bef-8e3c-76ed9db2904a',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Saudi Arabia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd71df1b8-bc68-4f62-997c-895d904b375f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Commonwealth of Independent States',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd78235d8-93a3-48be-8ba7-cc066e48323a',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Chile',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd83d1ef5-865c-4dc8-9826-2e599b2cd5d5',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Papua New Guinea',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd8e28632-3773-4c8d-acc9-96ba5f5eaf94',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'South Asia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd9e4488e-f1c4-48a4-a714-b2ab34d7c768',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Japan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'da0801eb-2cb4-4e9b-8a49-be9ed54926c8',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Other',
    'description' => '',
    'format' => 'html',
    'weight' => 14,
    'uuid' => 'db788bef-e6b3-4e48-9ee0-0d31fb50407d',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Cocos (Keeling) Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dbeacb83-b29c-4ae1-868e-bb07e6d204f9',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Mobile app',
    'description' => '',
    'format' => 'html',
    'weight' => 22,
    'uuid' => 'dcc27be7-b817-4f29-9822-4be580a50411',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Senegal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dcfb1bc0-211a-44dd-932c-b6609965d251',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Uganda',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dead0cc9-6e9f-4281-94d7-8f4ce0f8abc9',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'St. Vincent and the Grenadines',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dffa565c-9036-4325-b68b-7878ea431c0a',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Netherlands Antilles',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e02865cd-8c70-4ea9-86e9-010ab01384c2',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Bahamas, The',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e0381217-c8d7-410b-9daa-adc853bb5972',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Gabon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e0d48891-954b-4bbf-958d-97fd51ddb13e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Cuba',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e0f04b8b-7301-46a7-9633-6c0a5daaf092',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Монгол (Mongolian)',
    'description' => '',
    'format' => 'html',
    'weight' => 6,
    'uuid' => 'e1788a76-6e5a-4590-8e66-4b3c2cbce18c',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Français (French)',
    'description' => '',
    'format' => 'html',
    'weight' => 10,
    'uuid' => 'e24230d5-f759-45b2-971d-7d347876a06e',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Sudan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e4cfb5e1-eee6-4bf5-aadb-e5773364ed4a',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Cook Islands',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e57a51c4-3edc-42b2-a0e1-f9190196b9fb',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'French Guiana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e5ba7e19-0d6d-4d76-bbca-4ca1be95cee0',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Moldova',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e6670c1a-e1a7-4a37-bed0-9aaf9a0ce3b8',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Other',
    'description' => '',
    'format' => 'html',
    'weight' => 6,
    'uuid' => 'e7a42632-0795-4470-baf6-78f16306d08a',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'South Asia',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => 'e7b1c168-c92f-46c4-8071-68f189eb4c7d',
    'vocabulary_machine_name' => 'economy_coverage',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Botswana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e7b2245a-8822-49e2-b79a-92aa4ec5ae1d',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Eritrea',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e7ca344f-9dbc-461d-a10b-545210cd8ea6',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Austria',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e8d3a0ec-052a-4b83-9815-a9e6c5f29a26',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Pitcairn',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e906a336-f0bd-45e8-a209-95dc2cc62faa',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Nauru',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e9ef7d00-937b-4784-a01c-88a6fe6ca190',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Tokelau',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eacebac4-ced0-462f-9cc2-1c3cd316059e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Public',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => 'eb8b1da5-ac82-4f8a-a5de-b7d7eb896956',
    'vocabulary_machine_name' => 'data_classification',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'APF',
    'description' => '',
    'format' => 'html',
    'weight' => 7,
    'uuid' => 'ec14ae6d-44d3-4a4d-9398-ed01cf5d7d6a',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Singapore',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ecd40c7c-2e64-4fe3-8e1e-0cc9c0a3cbdb',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Liechtenstein',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ef7ce945-76c1-4796-aeda-e1c4149c2d60',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Kyrgyz Republic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ef84ae19-01f6-44db-8ab3-09f160079e14',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Seychelles',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'efb05d1b-53e7-4598-b50f-c667978f44e8',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Bangladesh',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f015a0c1-2262-4e2f-a8e2-1f8ffd2c8c1b',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Archived',
    'description' => '',
    'format' => 'html',
    'weight' => 8,
    'uuid' => 'f11a8c4d-b14c-4158-bc98-300ba08ceb9c',
    'vocabulary_machine_name' => 'update_frequency',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Türkçe (Turkish)',
    'description' => '',
    'format' => 'html',
    'weight' => 15,
    'uuid' => 'f200b982-86e3-4aea-9fd6-6fc38a25bc6a',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Ireland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f3dc0cec-a875-4cf1-9af5-6adc5542c22a',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'El Salvador',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f3e3a3f9-3b8a-4257-9383-383d7f78501e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Ukraine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f4190648-6cb9-4654-8c5b-8d3ac640bf7e',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'DOC',
    'description' => '',
    'format' => 'html',
    'weight' => 4,
    'uuid' => 'f42cb0b3-531c-46b9-a77c-f4b5c0b0b834',
    'vocabulary_machine_name' => 'document_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Dataset',
    'description' => '',
    'format' => 'html',
    'weight' => 0,
    'uuid' => 'f5f4965c-81a3-4743-abd4-203be2a702f4',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Bahasa Indonesia (Indonesian)',
    'description' => '',
    'format' => 'html',
    'weight' => 20,
    'uuid' => 'f7be5c54-69ab-46c4-9962-dc3bafcfb284',
    'vocabulary_machine_name' => 'languages_supported',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Metadata',
    'description' => '',
    'format' => 'html',
    'weight' => 11,
    'uuid' => 'fa49baeb-366b-42da-bd7f-2b521fd8d8a7',
    'vocabulary_machine_name' => 'resource_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Peru',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fba34f2f-3172-49fa-8631-fb0ceea18924',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Geospatial',
    'description' => 'This is a dynamic traffic map service with capabilities for visualizing traffic speeds relative to expected averages.',
    'format' => 'html',
    'weight' => 0,
    'uuid' => 'fbcb7053-4dc3-4748-8ed7-2d4ed86ec71a',
    'vocabulary_machine_name' => 'data_type',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Timor-Leste',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fcee8780-02a7-4264-a04a-93741b628dbf',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Iceland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fd124642-06ac-488a-b9db-956317fa450f',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Russian Federation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'feb30b1a-2a4d-45cd-a07d-58a931f61951',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'China',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fed5126b-3742-4efe-a977-2cd68cc88c68',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Algeria',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ff1c1f09-cf94-400a-97da-7783840248b4',
    'vocabulary_machine_name' => 'country',
  );
  $terms[] = array(
    'name' => 'Kosovo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ff958d27-2248-48f9-a485-a9c31e0ca9fd',
    'vocabulary_machine_name' => 'country',
  );
  return $terms;
}
