version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04 
    working_directory: /go/src/github.com/dkan_starter
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - setup_remote_docker
      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Updates etc 
          command: |
            apt-get update
            apt-get upgrade -y
            apt-get install curl wget -y
      - run:
          name: Install Ahoy
          command: |
            wget -q https://github.com/devinci-code/ahoy/releases/download/1.1.0/ahoy-`uname -s`-amd64 -O /usr/local/bin/ahoy &&
            chmod +x /usr/local/bin/ahoy
            ahoy
      - run:
          name: Start container and verify it's working
          command: |
            cp dkan/.ahoy/docker-compose.common.yml docker-compose.yml
            cp dkan/.ahoy/mysql.env mysql.env 
            docker cp .ahoy $(docker-compose ps -q cli):/var/www
            docker cp .ahoy.yml $(docker-compose ps -q cli):/var/www
            docker cp docroot $(docker-compose ps -q cli):/var/www
            docker cp config $(docker-compose ps -q cli):/var/www
            docker cp assets $(docker-compose ps -q cli):/var/www
            docker cp dkan $(docker-compose ps -q cli):/var/www
            docker cp hooks $(docker-compose ps -q cli):/var/www
            export AHOY_CMD_PROXY=DOCKER
            env | grep AHOY
            ahoy docker up
            ahoy cmd-proxy ls -l
            ahoy utils setup
            ahoy site reinstall
            ahoy ci deploy
      - run:
          name: Run tests 
          command: |
            ahoy cmd-proxy bash dkan/.ahoy/.scripts/composer-install.sh
            b64=`echo "payload: $input" | base64 $wrap 0`
            ahoy cmd-proxy ruby dkan/.ahoy/.scripts/dkan-test.rb "$b64" --skip-composer

