version: 2
## Customize the test machine

jobs:
  build:
    working_directory: ~/site_build
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      CIRCLE_ARTIFACTS: "/home/circleci/site_build/assets/tests"
    parallelism: 5
    docker:
      - image: circleci/php:5.6.31-apache-node-browsers
        environment:
          MYSQL_HOST: "127.0.0.1"
          DATABASE_URL: "mysql://drupal:123@127.0.0.1:3306/drupal"
          MYSQL_USER: "drupal"
          MYSQL_PASSWORD: "123"
          MYSQL_DATABASE: "drupal"
      - image: circleci/mariadb:10.3.3-ram
        command: --secure-file-priv='' --max-allowed-packet=128M --innodb-buffer-pool-size=256M
        environment:
          - MYSQL_ROOT_PASSWORD=
          - MYSQL_USER=drupal
          - MYSQL_PASSWORD=123
          - MYSQL_DATABASE=drupal
      # Selenium image won't start, running via npm install
      #- image: selenium/standalone-chrome-debug:2.53.1
    steps:
      - restore_cache:
          keys:
            - v1-dkan-{{ .Branch }}
            - v1-dkan-test-vendor
      - run:
          name: Install Chrome
          command: |
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb

      - run:
          name: Install Selenium
          command: |
            sudo npm install selenium-standalone@latest -g
            #npm install geckodriver
            sudo selenium-standalone install --drivers.chrome.version=2.37 --drivers.chrome.baseURL=https://chromedriver.storage.googleapis.com

      - run:
          name: Run Selenium
          command: |
            sudo selenium-standalone start
          background: true
      - run:
          name: Update Packages
          command: sudo apt-get update
      - run:
          name: Install Packages
          command: sudo apt-get install -y ruby libpng-dev libmcrypt-dev mysql-client x11vnc

#Available Extensions:
#bcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap interbase intl json ldap mbstring mcrypt mssql mysql mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml snmp soap sockets spl standard sybase_ct sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd json mcrypt mysql mysqli opcache pdo pdo_mysql zip
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
            composer global require hirak/prestissimo
            echo 'export PATH=~/.composer/vendor/bin:$PATH' >> $BASH_ENV
      - run:
          name: Edit MySQL Configuration
          command: |
            mysql -uroot -e "grant FILE on *.* to 'drupal'@'%'"
            sudo chmod 777 /etc/mysql/my.cnf
            sudo echo -e "[client]\nloose-local-infile" >> /etc/mysql/my.cnf
            sudo chmod 644 /etc/mysql/my.cnf
      - run:
          name: Adjust PHP Settings
          command: |
            sudo chmod 777 /usr/local/etc/php/conf.d
            echo "memory_limit = 512M" > /usr/local/etc/php/conf.d/memory.ini
            echo "always_populate_raw_post_data = -1" > /usr/local/etc/php/conf.d/deprecated.ini
      - checkout
      - run: php -i

#################################
#DKAN Starter Modifications BEGIN
#################################
      - run:
          name: DKAN Starter Configuration
          command: |
            #Create "db" hosts since all in one container
            sudo sh -c "echo 'db 127.0.0.1' >> /etc/hosts"
            sudo apt-get install -y clamav clamav-freshclam
            sudo wget -O - https://install.perlbrew.pl | bash
            ~/perl5/perlbrew/bin/perlbrew install-cpanm
            sudo ~/perl5/perlbrew/bin/cpanm install Digest::HMAC_SHA1
###############################
#DKAN Starter Modifications END
###############################
      - run:
          name: Setup Apache
          command : |
            sudo cp .circleci/tests/circle/circle.conf /etc/apache2/sites-available
            sudo a2dissite 000-default
            sudo a2ensite circle.conf
            sudo a2enmod rewrite
            sudo service apache2 restart

      # Ahoy install in dkan-init.sh had problems detecting root user.
      - run:
          name: Install Ahoy
          command: |
            sudo wget -q https://github.com/devinci-code/ahoy/releases/download/1.1.0/ahoy-`uname -s`-amd64 -O /usr/local/bin/ahoy &&
            sudo chmod +x /usr/local/bin/ahoy

      ### Setup DKAN
#################################
#DKAN Starter Modifications BEGIN
#################################
      - run:
          name: DKAN Initialization
          command: |
            # bash dkan-init.sh dkan --deps --build=$DATABASE_URL
            bash dkan/dkan-init.sh dkan --deps-only
            drush dl -n registry_rebuild-7.x
            #ahoy drush --yes en dkan_harvest dkan_harvest_datajson dkan_harvest_dashboard
            #ahoy drush cc all
###############################
#DKAN Starter Modifications END
###############################
      - run:
          name: Server Router Background Server Task
          command: ahoy dkan server
          background: true
      - run:
          name: X11 VNC Background Server Task
          command: x11vnc -forever -nopw
          background: true

#################################
#DKAN Starter Modifications BEGIN
#################################
#      - run:
#          name: Enable dkan_harvest_test and reinstall
#          command: |
#            ahoy drush en --yes dkan_harvest_test
#            ahoy dkan reinstall --yes
      - run:
          name: DKAN Starter Site Up
          command: |
            ahoy site up --db-user=drupal --db-pass=123 --db-host=127.0.0.1 --db-name=drupal
            ahoy utils fail-when-bad-disable
###############################
#DKAN Starter Modifications END
###############################
      - save_cache:
          key: v1-dkan-{{ .Branch }}
          paths:
            - ~/.drush
            - ~/.composer
      - save_cache:
          key: v1-dkan-test-vendor
          paths:
            - dkan/test/vendor
#################################
#DKAN Starter Modifications BEGIN
#################################
      - run:
          name: Run Parallel Behat Tests
#         command: ruby dkan/.ahoy/.scripts/circle-behat.rb docroot/profiles/dkan/test/features
          command: |
            mkdir -p $CIRCLE_ARTIFACTS/junit
            BEHAT_FOLDER=/home/circleci/site_build/tests ruby dkan/.ahoy/.scripts/circle-behat.rb tests/features dkan/test/features tests/features dkan/test/features config/tests/features --tags='~@customizable&&~@fixme&&~@testBug'
###############################
#DKAN Starter Modifications END
###############################
      # Lint only on 1st parallel instance. Deploy: blocks until parallelism is done, so doing it this way.
      - run:
          name: Run Lint
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "0" ]; then
              ahoy dkan lint
            fi
      # Unit Tests only on 1st parallel instance. Deploy: blocks until parallelism is done, so doing it this way.
      - run:
          name: Run PHPUnit Tests
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "0" ]; then
              ahoy dkan unittests
            fi
      - store_artifacts:
          path: ~/site_build/dkan/test/assets
  build_php71:
    working_directory: ~/site_build
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      CIRCLE_ARTIFACTS: "/home/circleci/site_build/assets/tests"
    parallelism: 5
    docker:
      - image: pythagory/dkan-web:7-latest
        environment:
          MYSQL_HOST: "127.0.0.1"
          DATABASE_URL: "mysql://drupal:123@127.0.0.1:3306/drupal"
          MYSQL_USER: "drupal"
          MYSQL_PASSWORD: "123"
          MYSQL_DATABASE: "drupal"
      - image: circleci/mariadb:10.3.3-ram
        command: --secure-file-priv='' --max-allowed-packet=128M --innodb-buffer-pool-size=256M
        environment:
          - MYSQL_ROOT_PASSWORD=
          - MYSQL_USER=drupal
          - MYSQL_PASSWORD=123
          - MYSQL_DATABASE=drupal
      # Selenium image won't start, running via npm install
      #- image: selenium/standalone-chrome-debug:2.53.1
    steps:
      - restore_cache:
          keys:
            - v1-dkan-{{ .Branch }}
            - v1-dkan-test-vendor
      # Selenium is already installed, run it
      - run:
          name: Run Selenium
          command: |
            sudo selenium-standalone start
          background: true
#################################
#DKAN Starter Modifications BEGIN
#################################
      - run:
          name: DKAN Starter Configuration
          command: |
            sudo sh -c "echo 'db 127.0.0.1' >> /etc/hosts"
            sudo wget -O - https://install.perlbrew.pl | bash
            ~/perl5/perlbrew/bin/perlbrew install-cpanm
            sudo ~/perl5/perlbrew/bin/cpanm install Digest::HMAC_SHA1
###############################
#DKAN Starter Modifications END
###############################
      - checkout
      - run: php -i
      - run:
          name: Setup Apache
          command : |
            sudo cp .circleci/tests/circle/circle.conf /etc/apache2/sites-available
            sudo a2dissite 000-default
            sudo a2ensite circle.conf
            sudo a2enmod rewrite
            sudo service apache2 restart

      # Ahoy install in dkan-init.sh had problems detecting root user.
      - run:
          name: Install Ahoy
          command: |
            sudo wget -q https://github.com/devinci-code/ahoy/releases/download/1.1.0/ahoy-`uname -s`-amd64 -O /usr/local/bin/ahoy &&
            sudo chmod +x /usr/local/bin/ahoy

      ### Setup DKAN
#################################
#DKAN Starter Modifications BEGIN
#################################
      - run:
          name: DKAN Initialization
          command: |
            #bash dkan-init.sh dkan --deps --build=$DATABASE_URL
            bash dkan/dkan-init.sh dkan --deps-only
            drush dl -n registry_rebuild-7.x
            #ahoy drush --yes en dkan_harvest dkan_harvest_datajson dkan_harvest_dashboard
            #ahoy drush cc all
###############################
#DKAN Starter Modifications END
###############################
      - run:
          name: Server Router Background Server Task
          command: ahoy dkan server
          background: true
      - run:
          name: X11 VNC Background Server Task
          command: x11vnc -forever -nopw
          background: true

#################################
#DKAN Starter Modifications BEGIN
#################################
#      - run:
#          name: Enable dkan_harvest_test and reinstall
#          command: |
#            ahoy drush en --yes dkan_harvest_test
#            ahoy dkan reinstall --yes
      - run:
          name: DKAN Starter Site Up
          command: |
            ahoy site up --db-user=drupal --db-pass=123 --db-host=127.0.0.1 --db-name=drupal
            ahoy utils fail-when-bad-disable
###############################
#DKAN Starter Modifications END
###############################
      - save_cache:
          key: v1-dkan-{{ .Branch }}
          paths:
            - ~/.drush
            - ~/.composer
      - run:
          name: Edit MySQL Configuration
          command: |
            mysql -uroot -e "grant FILE on *.* to 'drupal'@'%'"
      - save_cache:
          key: v1-dkan-test-vendor
          paths:
            - dkan/test/vendor
# Uncomment for local testing to sleep before testing.
#      - run:
#          command: sleep 1d
#          no_output_timeout: 1h

      - run:
          name: Run Parallel Behat Tests
          command: |
            mkdir -p $CIRCLE_ARTIFACTS/junit
            BEHAT_FOLDER=/home/circleci/site_build/tests ruby dkan/.ahoy/.scripts/circle-behat.rb tests/features dkan/test/features tests/features dkan/test/features config/tests/features --tags='~@customizable&&~@fixme&&~@testBug'

      # Lint only on 1st parallel instance. Deploy: blocks until parallelism is done, so doing it this way.
      - run:
          name: Run Lint
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "0" ]; then
              ahoy dkan lint
            fi
      # Unit Tests only on 1st parallel instance. Deploy: blocks until parallelism is done, so doing it this way.
      - run:
          name: Run PHPUnit Tests
          command: |
            if [ "$CIRCLE_NODE_INDEX" -eq "0" ]; then
              ahoy dkan unittests
            fi
      - store_artifacts:
          path: ~/site_build/dkan/test/assets


#Workflow to only run PHP 7 build if branch name contains php7
#TODO - filter to run PHP71 on releases
workflows:
  version: 2
  build_php5:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*php7.*/
  build_php5_php7:
    jobs:
      - build:
          filters:
            branches:
              only: 7.x-1.x
      - build_php71:
          requires:
            - build
  build_php7:
    jobs:
      - build_php71:
          filters:
            branches:
              only: /.*php7.*/
