version: 2
## Customize the test machine

jobs:
  build:
    working_directory: ~/site_build
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      CIRCLE_ARTIFACTS: "/home/circleci/site_build/assets/tests"
    parallelism: 5
    docker:
      - image: nuams/drupal-apache-php:1.0-5.6
        hostname: web
        ports:
          - "80"
          - "443"
          - "8888"
        links:
          - db
          # Uncomment this and the memcached service definition below to start using memcached.
          - memcached
          - solr
        volumes:
          # PHP configuration overrides
          - "./.docker/etc/php5/php.ini:/etc/php5/fpm/conf.d/z_php.ini"
          - "./.docker/etc/php5/xdebug-linux.ini:/etc/php5/xdebug-linux.ini"
          - "./.docker/etc/php5/xdebug-macos.ini:/etc/php5/xdebug-macos.ini"
        network_mode: bridge
        labels:
          - "traefik.frontend.rule=Host:${SLUG}.${PROXY_DOMAIN}"
          - "traefik.frontend.passHostHeader=true"
        environment:
          # no_proxy="" required for default Docker For Mac system proxy that contains a space and prevents Selenium from loading.
          # Linked containers to browser will also need this setting.
          - no_proxy=""
      - image: wodby/mariadb:latest
        hostname: db
        ports:
          - "3306"
        # MYSQL Credentials in mysql.env
        env_file:
          - mysql.env
        volumes:
           # MySQL configuration overrides
           - "./.docker/etc/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf"
           # Permanent DB data storage
           - /var/lib/mysql
        labels:
          - traefik.enable=false
        network_mode: bridge
      - image: nuams/drupal-cli:2016-10-16
        hostname: cli
        environment:
          - XDEBUG_CONFIG=idekey=PHPSTORM
        env_file:
          - mysql.env
        links:
          - db
          - web
          # Uncomment this and the browser service definition below to start using selenium2.
          - browser
          - memcached
          - solr
        ports:
          - "8888"
        volumes:
          # PHP configuration overrides
          - "./.docker/etc/php5/php-cli.ini:/etc/php5/cli/conf.d/z_php.ini"
          - "./.docker/etc/php5/xdebug-linux.ini:/etc/php5/xdebug-linux.ini"
          - "./.docker/etc/php5/xdebug-macos.ini:/etc/php5/xdebug-macos.ini"
          # Host SSH keys mapping. Uncomment one of the lines below based on your setup.
          - ~/.ssh:/.ssh
        labels:
          - traefik.enable=false
        network_mode: bridge
      - image: memcached
        hostname: memcached
        environment:
          # Memcached memory limit in megabytes
          - MEMCACHED_MEMORY_LIMIT=128
        labels:
          - traefik.enable=false
        network_mode: bridge
      - image: selenium/standalone-chrome-debug:2.53.1
        hostname: browser
        # This helps keep selenium-chrome from crashing because it uses shared memory.
        ports:
          - "5900"
        volumes:
          - /dev/shm:/dev/shm
          # Project root folder mapping
          - "../../:/var/www/"
        links:
          - web
        environment:
          # no_proxy="" required for default Docker For Mac system proxy that contains a space and prevents Selenium from loading.
          - no_proxy=""
        network_mode: bridge
        labels:
          - traefik.enable=false
      - image: devinci/drupal-solr:3.x
        hostname: solr
        ports:
          - "8983"
        volumes:
          - "./.docker/etc/solr/3.x:/var/lib/solr/conf"
        labels:
          - "traefik.frontend.rule=Host:${SLUG}-solr.${PROXY_DOMAIN}"
        network_mode: bridge
    steps:
      - run:
          name: Install Chrome
          command: |
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb

      - run:
          name: Install Selenium
          command: |
            sudo npm install selenium-standalone@latest -g
            #npm install geckodriver
            sudo selenium-standalone install
            
      - run:
          name: Run Selenium
          command: |
            sudo selenium-standalone start
          background: true
      - run:
          name: Update Packages
          command: sudo apt-get update
      - run:
          name: Install Packages
          command: sudo apt-get install -y ruby libpng-dev libmcrypt-dev mysql-client x11vnc

#Available Extensions:
#bcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap interbase intl json ldap mbstring mcrypt mssql mysql mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml snmp soap sockets spl standard sybase_ct sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd json mcrypt mysql mysqli opcache pdo pdo_mysql zip
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
            composer global require hirak/prestissimo
            echo 'export PATH=~/.composer/vendor/bin:$PATH' >> $BASH_ENV
      - run:
          name: Edit MySQL Configuration
          command: |
            mysql -uroot -e "grant FILE on *.* to 'drupal'@'%'"
            sudo chmod 777 /etc/mysql/my.cnf
            sudo echo -e "[client]\nloose-local-infile" >> /etc/mysql/my.cnf
            sudo chmod 644 /etc/mysql/my.cnf
      - run:
          name: Adjust PHP Settings
          command: |
            sudo chmod 777 /usr/local/etc/php/conf.d
            echo "memory_limit = 512M" > /usr/local/etc/php/conf.d/memory.ini
            echo "always_populate_raw_post_data = -1" > /usr/local/etc/php/conf.d/deprecated.ini
      - checkout
      - run: php -i
workflows:
  version: 2
  build_php5:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*php7.*/
  build_php5_php7:
    jobs:
      - build:
          filters:
            branches:
              only: 7.x-1.x
      - build_php71:
          requires:
            - build
  build_php7:
    jobs:
      - build_php71:
          filters:
            branches:
              only: /.*php7.*/
