<?php
/**
 * @file
 * Code for the HHS Search feature.
 */

include_once 'dkan_acquia_search_solr.features.inc';

function dkan_acquia_search_solr_default_search_api_server_alter(array &$defaults) {

  // List of the possible search api indexes.
  $server_list = array(
    "groups_server",
    "datasets",
    "dkan_acquia_solr",
    "local_solr_server",
    "stories_server",
    "acquia_solr_server"
  );

  // Disable ALL servers by default.
  foreach($server_list as $server) {
    if (isset($defaults[$server])) {
      $defaults[$server]->enabled = false;
    }
  }

  // Check if a custom server has been set in $settings.php or elsewhere.
  if (!$server_override = variable_get('dkan_acquia_search_solr_override', false)) {
    // No override is set so enable the acquia server.
    $defaults["dkan_acquia_solr"]->enabled = true;
  }
  else {
    $defaults[$server_override]->enabled = true;
  }

}