<?php



/**
 * Implements hook_preprocess_node().
 */
function custom_dash_preprocess_node(&$variables) {
  if($variables['type'] == 'react_dashboard') {

    $css = drupal_get_path('module', 'custom_dash') . '/css/customDash.css';
    if(file_exists($css)) drupal_add_css($css);

    $js = drupal_get_path('module', 'custom_dash') . '/js/customDash.js';
    if(file_exists($js)) drupal_add_js($js, array('scope' => 'footer', 'weight' => 0));
  }
}