---
acquia:
  dev:
    base_url: http://devurl
    core_id: changeme
    derived_key: changeme
  prod:
    base_url: http://produrl
    core_id: changeme
    derived_key: changeme
  ra:
    base_url: http://testurl
    core_id: changeme
    derived_key: changeme
  search:
    host: changeme
    id: dkan_acquia_solr
  subscription: professional
  test:
    base_url: http://testurl
    core_id: changeme
    derived_key: changeme
circle:
  memory_limit: 256M
  skip_features: []
  skip_tags:
  - customizable
  - fixme
  - testBug
  test_dirs:
  - tests/features
  - dkan/test/features
  - config/tests/features
default:
  clamav:
    enable: false
  dkan_workflow:
    enable: false
  fast_file:
    enable: true
    limit: 10MB
    queue: 50MB
  hostname: www.example.com
  https_everywhere: false
  https_securepages: false
  odfe:
    enable: false
  stage_file_proxy_origin: changeme
gaClientTrackingCode: UA-XXXXX-Y
gaNuCivicTrackingCode: UA-XXXXX-Z
private:
  aws:
    scrubbed_data_url: CHANGE ME
  probo:
    password: CHANGE ME
redirectDomains:
- example.com
- oldsite.example.com
