default:
  hostname: localhost
  https_everywhere: FALSE
  https_securepages: FALSE
  stage_file_proxy_origin: changeme
  fast_file:
    enable: TRUE
    limit: 10MB
    queue: 50MB
acquia:
  subscription: 'professional'
  search:
    host: changeme
    id: dkan_acquia_solr 
  dev:
    base_url: http://devurl
    core_id: changeme
    derived_key: changeme
  test:
    base_url: http://testurl
    core_id: changeme
    derived_key: changeme
  ra:
    base_url: http://testurl
    core_id: changeme
    derived_key: changeme
  prod:
    base_url: http://produrl
    core_id: changeme
    derived_key: changeme
    
