ahoyapi: v2
version: 0.0.0
commands:
  deploy:
    usage: Runs the data_starter custom deployment step.
    cmd: |
      echo "TODO: add your custom deploy steps if any."
      ahoy ci deploy

  setup:
    usage: Sets up all the step
    cmd: |
      echo "TODO: add your custom setup steps if any."
      ahoy ci setup

  remake:
    usage: Rebuild all the dkan projects from the build.make file + custom postbuild.
    cmd: |
      set -e
      ahoy site remake
      ahoy custom post-build

  post-build:
    usage: Runs custom post-build commands.
    cmd: |
      echo "TODO: custom postbuild steps."
