<?php

/**
 * @file
 * Required module file.
 */

/**
 * Deregisters DKAN migrations.
 */
function dkan_migrate_base_migrations_disable() {
  Migration::deregisterMigration('ckan_dataset_base');
  Migration::deregisterMigration('ckan_group_base');
  Migration::deregisterMigration('ckan_resource_base');
  Migration::deregisterMigration('datajson_dataset_base');
}

/**
 * Creates resource list from CKAN site.
 *
 * CKAN has no resource_list endpiont. This function creates a file that mimics
 * that. The file created is the public file name so return not supplied.
 */
function dkan_migrate_base_create_resource_list($endpoint, $file_name = 'public://ckan-migrate-resource_list', $update = FALSE) {
  // Update if requested or the file doesn't exist.
  if ($update || (!$update && !file_exists($file_name))) {
    $resource_ids = dkan_migrate_base_create_resource_list_items($endpoint, $file_name);
    file_unmanaged_save_data(json_encode($resource_ids), $file_name, FILE_EXISTS_REPLACE);
  }
}

/**
 * Restrieves resource list from CKAN site.
 *
 * @return array
 *   List of resource uuids.
 */
function dkan_migrate_base_create_resource_list_items($endpoint, $file_name) {
  $package_list = $endpoint . 'package_list';
  $resource_ids = array('help' => t('List of resource ids for %endpoint', array('endpoint' => $endpoint)));
  $item_url = $endpoint . 'package_show?id=:id';
  if (substr($package_list, 0, 6) !== 'http://') {
    $json = file_get_contents($package_list);
  }
  else {
    $response = drupal_http_request($package_list);
    $json = $response->data;
  }
  $data = drupal_json_decode($json);
  foreach ($data['result'] as $id) {
    $dataset_show = preg_replace(array_fill(0, count($id), '/:id/'), $id, $item_url, 1);
    if (substr($dataset_show, 0, 6) !== 'http://') {
      $dataset_json = file_get_contents($dataset_show);
    }
    else {
      $dataset_response = drupal_http_request($dataset_show);
      $dataset_json = $dataset_response->data;
    }
    $dataset_data = drupal_json_decode($dataset_json);
    $resources = $dataset_data['result']['resources'];
    foreach ($resources as $key => $resource) {
      $resource_ids['result'][] = $resource['id'];
    }
  }
  file_unmanaged_save_data(json_encode($resource_ids), $file_name, FILE_EXISTS_REPLACE);
  return $resource_ids;
}

/**
 * Converts ISO 8061 dates with internvals into Unix timestamps.
 */
function dkan_migrate_base_iso_interval_to_timestamp($date) {
  $to = $from = NULL;
  $date = explode("/", $date);
  if ($date) {
    $dateTime = new DateTime($date[0]);
    $dateTime->format(DateTime::ISO8601);
    $from = $dateTime-> getTimestamp();
      if (isset($date[1])) {
      if ($to = strtotime($date[1])) {
      }
      else {
        $dateTime->add(new DateInterval($date[1]));
        $to = $dateTime-> getTimestamp();
      }
    }
  }
  return array(
    'to' => $to,
    'from' => $from
  );
}
