<?php
/**
 * @file
 * Code for the Visualization Entity Tables feature.
 */

include_once 'visualization_entity_tables.features.inc';

/**
 * Implements hook_form_alter().
 */
function visualization_entity_tables_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'eck__entity__form_add_visualization_ve_table':
    case 'eck__entity__form_edit_visualization_ve_table':
      visualization_entity_tables_attach_libraries($form);
      $module_path = drupal_get_path('module', 'visualization_entity_tables');
      drupal_add_js($module_path . '/js/visualization_entity_tables_edit.js', array('weight' => 102));
      break;
  }
}


/**
 * Attach needed libraries to an element.
 */
function visualization_entity_tables_attach_libraries(&$element) {
  $libraries = array(
    'lodash',
    'backbone',
    'recline',
    'gdocs',
    'csv',
    'mustache',
    'slickgrid',
  );

  foreach ($libraries as $library) {
    $element['#attached']['libraries_load'][] = array($library);
  }

  $module_path = drupal_get_path('module', 'visualization_entity_tables');
  $element['#attached']['css'][] = $module_path . '/css/ve_tables.css';
}

/**
 * Implements hook_entity_view().
 */
function visualization_entity_tables_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type == 'visualization' && $entity->type == 've_table') {
    if(visualization_entity_resource_accesible($entity, 'field_uuid_resource')){

      $entity->content['#suffix'] = '<div id="ve-table"></div>';
      visualization_entity_tables_attach_libraries($entity->content);
      $wrapper = entity_metadata_wrapper('visualization', $entity, array('bundle' => 've_table'));
      $settings = json_decode($wrapper->field_ve_settings->value());
      $resource = $settings->source;

      if(!empty($entity->field_uuid_resource[LANGUAGE_NONE][0]['target_uuid'])) {
        $settings->resource_uuid = $resource_uuid = $entity->field_uuid_resource[LANGUAGE_NONE][0]['target_uuid'];
      } else {
        $re = "/\\/node\\/([a-zA-Z0-9-]+)\\/download/";
        if(preg_match($re, $resource, $matches)) {
          $resource_uuid = $matches[1];
        }
      }

      $nids = entity_get_id_by_uuid('node', array($resource_uuid));
      $datastore = $table = FALSE;

      if(!empty($nids)){
        $node = node_load(current($nids));

        $resource_wrapper = entity_metadata_wrapper('node', $node);
        $fileType = $resource_wrapper->field_upload->value();
        $fileType = $fileType->filemime;
        $nid = $nids[$resource_uuid];

        if($resource_wrapper->field_datastore_status->value() == 1) {
          if (module_exists('dkan_datastore_api') && module_exists('feeds_flatstore_processor') && function_exists('dkan_datastore_api_get_feeds_source')) {
            $source_id = dkan_datastore_api_get_feeds_source($nid);
            if ($table = feeds_flatstore_processor_table_name($source_id, $nid)) {
              if (db_table_exists($table)) {
                $datastore = !!$table;
              }
            }
          }
        }
      }

      $settings->resource_uuid = $resource_uuid;

      // Get value of Show title field.
      $title_wrapper = entity_metadata_wrapper('visualization', $entity);
      $showTitle = $title_wrapper->field_show_title->raw();
      if($showTitle) {
        $showTitle = $showTitle[0];
      }
      else {
        $showTitle = 0;
      }

      drupal_add_js(array(
          'visualizationEntityTables' => array(
            'resource' => $settings->source,
            'resize' => $settings->resize,
            'showTitle'=> $showTitle,
            'pager'=> $settings->pager,
            'numRecords'=> $settings->numRecords,
            'datastore' => $datastore,
            'resource_uuid' => $settings->resource_uuid,
            'fileType' => $fileType,
          )
        ),
      'setting');
      $recline_module_path = drupal_get_path('module', 'recline');
      drupal_add_js($recline_module_path . '/backend.ckan_get.js', array('type' => 'file', 'scope' => 'footer'));
      drupal_add_js(drupal_get_path('module', 'visualization_entity_tables') . '/js/visualization_entity_tables_view.js', array('weight' => 101));
    } else {
      drupal_access_denied();
    }
  }
}
