<?php

/**
 * Implements hook_init().
 */
function devinci_init() {
  // Set some items for the environment and environment_indicator (this is very light weight).
  if (defined('ENVIRONMENT') && function_exists('environment_current') && function_exists('environment_switch')) {
    $current_env = environment_current();
    if ($current_env != ENVIRONMENT) {
      environment_switch(ENVIRONMENT, TRUE);
    }
  }
}

/**
 * Implements hook_environment().
 */
function devinci_environment() {
  $environments = array();

  $environments['local'] = array(
    'label' => t('Local'),
    'description' => t('Local development environment'),
  );
  $environments['dev'] = array(
    'label' => t('Development'),
    'description' => t('Development modules are enabled, but use local for most dev.'),
  );
  $environments['test'] = array(
    'label' => t('Testing site'),
    'description' => t('Testing sites are used for QA or automated testing.'),
  );
  $environments['live'] = array(
    'label' => t('Live site'),
    'description' => t('Live sites are in full production and browsable on the web.'),
  );

  return $environments;
}

/**
 * Implements hook_environment_indicator_matched_indicator_alter().
 */
function devinci_environment_indicator_matched_indicator_alter(&$env) {
  // Base the indicator on our own settings.
  // that use the environment module.
  if (!defined('ENVIRONMENT')) {
    $env['name'] = 'unknown';
    return;
  }

  $real_env = ENVIRONMENT;
  $env['name'] = $real_env;
  switch ($real_env) {
    case 'local':
      $env['color'] = '#208f00';
      break;

    case 'dev':
      $env['color'] = '#e07a00';
      break;

    case 'test':
      $env['color'] = '#c41e02';
      break;

    case 'live':
      $env['color'] = '#5e5e5e';
      break;
  }
}

/**
 * Implementation of hook_environment_switch().
 */
function devinci_environment_switch($target_env, $current_env) {
  // Developers can define this function in settings.php and it will be called.
  if (function_exists('devinci_custom_environment_switch')) {
    devinci_custom_environment_switch($target_env, $current_env);
  }
  // TODO: additional devinci specific things to change on env change.
}
