ahoyapi: v1
usage: NuCivic Data cli app for development using ahoy.
commands:
  drush:
    usage: Run drush via ahoy (helpful for abstraction)
    cmd: ahoy cmd-proxy drush --root=docroot {{args}}

  dkan:
    usage: A series of commands for dkan development.
    import: dkan/.ahoy/dkan.ahoy.yml

  diagnose:
    usage: A series of ahoy-docker setup diagnosis commands.
    import: dkan/.ahoy/diagnose.ahoy.yml

  doctor:
    usage: A series of ahoy-docker setup diagnosis commands.
    import: dkan/.ahoy/diagnose.ahoy.yml

  confirm:
    cmd: ahoy -f dkan/.ahoy/utils.ahoy.yml confirm {{args}}
    hide: true

  docker:
    usage: A series of docker commands for dkan development (experimental)
    import: dkan/.ahoy/docker.ahoy.yml
    hide: true

  init:
    cmd: echo "ahoy.yml file already exists."
    hide: true

  cmd-proxy:
    usage: abstraction for commmands.
    cmd: |
      if [ "$AHOY_CMD_PROXY" == "DOCKER" ]; then
        ahoy docker exec "{{args}}"
      else
        {{args}}
      fi
    hide: true

  ci:
    usage: A series of commands to handle ci setup
    import: nucivic-ahoy/ci.ahoy.yml

  launch-checklist:
    usage: A series of commands to handle pre launch checks
    import: nucivic-ahoy/launch-checklist.ahoy.yml

  site:
    usage: A series of commands for site development
    import: nucivic-ahoy/site.ahoy.yml

  remote:
    usage: A series of commands for site remote management
    import: nucivic-ahoy/remote.ahoy.yml

  custom:
    usage: A series of custom commands specific to a project.
    import: .ahoy/custom.ahoy.yml
