<?php

/**
 * @file
 * Module file for dkan_harvest_example.
 */

/**
 * Implements hook_harvest_sources().
 */
function dkan_harvest_example_harvest_sources() {
  $sources = array(
    'data.mo.gov' => array(
      'remote' => 'https://data.mo.gov/data.json',
      'type' => 'data.json',
      'filters' => array(
        'theme' => array('Health'),
      ),
      'excludes' => array(
        'accessURL' => array('https://data.mo.gov/api/file_data/Q_A5PzJ6KjRSU6UpxbrdgR5-AV8bx6EarjcJavFYWog?filename=Letter+%26+Registration+Form+with+Map+smoke+with+classroom+date.pdf'),
      ),
      'defaults' => array(
        'agency' => 'State of Missouri',
        'author' => 'State of Missouri',
        'author_id' => 'http://healthdata.gov/id/state/mo',
        'catalog_type' => 'State Catalog',
      ),
      'overrides' => array(),
    ),
  );
  return $sources;
}
